name: Release

on: push

jobs:
  run-pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Test with pytest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-1"
          FETCH_BATCH_SIZE: ${{ secrets.FETCH_BATCH_SIZE }}
          APIGATEWAY_URL: ${{ secrets.APIGATEWAY_URL }}
          YELP_TABLE_NAME: ${{ secrets.YELP_TABLE_NAME }}
          URL_TABLE_NAME: ${{ secrets.URL_TABLE_NAME }}
          URL_TABLE_TTL: ${{ secrets.URL_TABLE_TTL }}
          PAGE_BUCKET_NAME: ${{ secrets.PAGE_BUCKET_NAME }}
          PAGE_FETCHER_LAMBDA_NAME: ${{ secrets.PAGE_FETCHER_LAMBDA_NAME }}
        run: |
          pip install -e .
          pip install pytest
          pip install pytest-cov
          python -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  deploy-cdk:
    name: Deploy cdk
    runs-on: ubuntu-latest
    needs: run-pytest
    steps:
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v1.1.10
        with:
          cdk_subcommand: "synth"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-1"
          FETCH_BATCH_SIZE: ${{ secrets.FETCH_BATCH_SIZE }}
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v1.1.10
        with:
          cdk_subcommand: "deploy"
          actions_comment: false
          args: "--require-approval never"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-1"
